name: first-workflow-test

on: push

jobs:
  first-workflow-job:

    runs-on: ubuntu-latest

    steps:
    - name: check out repository code
      uses: actions/checkout@v4
    - run: echo "$(cat hello_word.txt)"
